<a href="https://colab.research.google.com/github/hota15/Time-Series-stock-market-analysis/blob/Sameer/Pesu_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv("TimeSeriesDataset.csv")

In [ ]:
df.size

4845

df. *describe* This funtion shows the number of elements in dataset.

In [ ]:
df.ndim

2

df. *describe* This function returns the dimensions of the dataset.

In [ ]:
df.describe()

,Open,High,Low,Close,Adj Close,Volume,Open.1,High.1,Low.1,Close.1,Adj Close.1,Volume.1,Open.2,High.2,Low.2,Close.2,Adj Close.2,Volume.2
count,253.000000,253.000000,253.000000,253.000000,253.000000,2.530000e+02,253.000000,253.000000,253.000000,253.000000,253.000000,2.530000e+02,253.000000,253.000000,253.000000,253.000000,253.000000,2.530000e+02
mean,421.893874,443.745257,404.388735,423.421937,408.628142,2.414973e+06,1126.181226,1173.802371,1087.527867,1128.578657,1062.268750,2.187884e+06,110.365613,116.445257,104.629645,109.869763,109.442157,1.707624e+06
std,203.609580,214.924889,195.169866,206.181560,212.943620,4.078128e+06,552.871833,572.758338,537.780367,558.261642,583.772081,2.746104e+06,60.228278,62.631394,58.176425,60.063111,60.251732,3.317936e+06
min,165.000000,191.800003,145.300003,181.550003,173.258652,3.399900e+04,470.000000,528.000000,470.000000,501.850006,459.752686,2.051900e+04,24.549999,27.500000,21.299999,25.799999,25.613701,6.176000e+04
25%,295.000000,308.000000,282.299988,290.850006,274.164154,2.249820e+05,750.000000,776.000000,719.000000,743.400024,653.323364,1.032320e+05,67.500000,72.449997,62.500000,65.900002,65.237930,2.663310e+05
50%,350.000000,365.000000,337.149994,348.049988,331.481293,9.082150e+05,940.000000,968.500000,896.000000,935.450012,843.896545,1.014178e+06,83.500000,87.949997,77.849998,82.550003,81.663971,6.809900e+05
75%,415.850006,440.000000,400.149994,419.450012,405.447205,3.017064e+06,1340.050049,1406.000000,1295.050049,1341.400024,1296.829102,3.381637e+06,181.100006,189.949997,172.000000,176.399994,176.399994,1.527140e+06
max,985.000000,1026.949951,968.099976,980.049988,980.049988,3.242625e+07,2792.250000,2811.800049,2721.550049,2774.250000,2774.250000,1.553717e+07,234.899994,257.750000,215.000000,228.699997,228.592758,3.516678e+07

df. *describe* This function shows statistical calculations like mean,percentile ,standard deviation , min,max etc

In [ ]:
df.sample()

,Dat+A1:G241e,Open,High,Low,Close,Adj Close,Volume,Open.1,High.1,Low.1,Close.1,Adj Close.1,Volume.1,Open.2,High.2,Low.2,Close.2,Adj Close.2,Volume.2
125,8/10/2020,457.0,481.700012,415.25,455.149994,434.363434,13411644.0,1033.0,1423.0,1001.0,1293.599976,1203.302002,14141975.0,73.949997,92.349998,70.0,88.849998,88.20842,9339641.0

df. *describe* This function generates a random row or column from the datset