<a href="https://colab.research.google.com/github/hota15/Time-Series-stock-market-analysis/blob/Tanistha/StockMarketAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df= pd.read_csv("TimeSeriesDataset.csv")

df.head() returns the first 5 values of the dataset

In [4]:
df.head()

,Dat+A1:G241e,Open,High,Low,Close,Adj Close,Volume,Open.1,High.1,Low.1,Close.1,Adj Close.1,Volume.1,Open.2,High.2,Low.2,Close.2,Adj Close.2,Volume.2
0,02-04-2018,399.000000,402.000000,386.250000,390.750000,348.683014,486346,1127.699951,1155.000000,1100.050049,1102.849976,939.665161,463619,115.000000,121.949997,113.849998,118.800003,117.198601,680990
1,09-04-2018,392.000000,393.000000,372.299988,375.700012,335.253265,338510,1100.500000,1150.000000,1080.099976,1123.050049,956.876221,352724,118.599998,127.900002,117.050003,123.849998,122.180527,1132548
2,16-04-2018,373.000000,421.899994,373.000000,415.600006,370.857788,1818906,1125.000000,1164.000000,1118.000000,1125.550049,959.006348,324581,121.500000,128.800003,118.800003,122.849998,121.194008,940794
3,23-04-2018,415.799988,421.000000,403.000000,405.000000,361.398956,358349,1132.000000,1149.000000,1122.000000,1125.800049,959.219238,137822,121.599998,131.399994,120.000000,121.849998,120.207481,1073345
4,30-04-2018,400.549988,411.399994,386.350006,388.850006,346.987610,172209,1134.400024,1134.400024,1089.199951,1093.550049,931.741211,68802,122.900002,124.349998,113.199997,115.599998,114.041733,443155

df.tail() returns the  last 5 values of the dataset

In [8]:
df.tail()

,Dat+A1:G241e,Open,High,Low,Close,Adj Close,Volume,Open.1,High.1,Low.1,Close.1,Adj Close.1,Volume.1,Open.2,High.2,Low.2,Close.2,Adj Close.2,Volume.2
248,02-01-2023,942.000000,963.849976,925.849976,937.099976,937.099976,1936956,2540.000000,2573.949951,2450.000000,2500.399902,2500.399902,2890918,189.949997,205.000000,184.550003,194.500000,194.500000,2753439
249,09-01-2023,941.000000,957.000000,913.000000,924.799988,924.799988,2576779,2517.000000,2542.000000,2435.550049,2462.750000,2462.750000,2591497,195.649994,199.199997,190.800003,191.899994,191.899994,554895
250,16-01-2023,928.950012,946.450012,916.549988,935.400024,935.400024,1339360,2450.000000,2522.000000,2406.000000,2509.500000,2509.500000,3251315,192.750000,198.899994,192.000000,192.649994,192.649994,501399
251,23-01-2023,939.700012,949.650024,862.650024,925.549988,925.549988,1007011,2528.000000,2550.000000,2418.100098,2465.000000,2465.000000,2524641,193.550003,199.449997,188.250000,192.100006,192.100006,676414
252,27-01-2023,925.000000,949.650024,862.650024,925.549988,925.549988,593843,2525.850098,2541.949951,2418.100098,2465.000000,2465.000000,801142,197.699997,199.449997,188.250000,192.100006,192.100006,281976

df.info() gives us an overview of the dataset

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253 entries, 0 to 252
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Dat+A1:G241e  253 non-null    object
 1   Open          253 non-null    float64
 2   High          253 non-null    float64
 3   Low           253 non-null    float64
 4   Close         253 non-null    float64
 5   Adj Close     253 non-null    float64
 6   Volume        253 non-null    int64
 7   Open.1        253 non-null    float64
 8   High.1        253 non-null    float64
 9   Low.1         253 non-null    float64
 10  Close.1       253 non-null    float64
 11  Adj Close.1   253 non-null    float64
 12  Volume.1      253 non-null    int64
 13  Open.2        253 non-null    float64
 14  High.2        253 non-null    float64
 15  Low.2         253 non-null    float64
 16  Close.2       253 non-null    float64
 17  Adj Close.2   253 non-null    float64
 18  Volume.2      253 non-null    int64
dtypes: float64(15), int64(3), object(1)
memory usage: 37.7+ KB

 df.shape returns the number of dimesnions and size in each dimension.

In [7]:
df.shape

(253, 19)