In [1]:
import numpy as np

In [2]:
import pandas as pd

In [5]:
df= pd.read_csv("TimeSeriesDataset.csv")

In [6]:
df.head()

,Unnamed: 0,Unnamed: 1,BDL,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,HAL,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,ZENTECH,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Dat+A1:G241e,Open,High,Low,Close,Adj Close,Volume,Open,High,Low,Close,Adj Close,Volume,Open,High,Low,Close,Adj Close,Volume
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,02-04-2018,399,402,386.25,390.75,348.683014,486346,1127.699951,1155,1100.050049,1102.849976,939.665161,463619,115,121.949997,113.849998,118.800003,117.198601,680990

In [7]:
df.head()

,Unnamed: 0,Unnamed: 1,BDL,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,HAL,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,ZENTECH,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Dat+A1:G241e,Open,High,Low,Close,Adj Close,Volume,Open,High,Low,Close,Adj Close,Volume,Open,High,Low,Close,Adj Close,Volume
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,02-04-2018,399,402,386.25,390.75,348.683014,486346,1127.699951,1155,1100.050049,1102.849976,939.665161,463619,115,121.949997,113.849998,118.800003,117.198601,680990

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257 entries, 0 to 256
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   254 non-null    object
 1   Unnamed: 1   254 non-null    object
 2   BDL          254 non-null    object
 3   Unnamed: 3   254 non-null    object
 4   Unnamed: 4   254 non-null    object
 5   Unnamed: 5   254 non-null    object
 6   Unnamed: 6   254 non-null    object
 7   Unnamed: 7   254 non-null    object
 8   HAL          254 non-null    object
 9   Unnamed: 9   254 non-null    object
 10  Unnamed: 10  254 non-null    object
 11  Unnamed: 11  254 non-null    object
 12  Unnamed: 12  254 non-null    object
 13  Unnamed: 13  254 non-null    object
 14  Unnamed: 14  254 non-null    object
 15  ZENTECH      254 non-null    object
 16  Unnamed: 16  254 non-null    object
 17  Unnamed: 17  254 non-null    object
 18  Unnamed: 18  254 non-null    object
dtypes: object(19)
memory usage: 38.3+ KB

In [9]:
df.shape

(257, 19)